# -*- coding: utf-8 -*-
from __future__ import annotations

import hashlib
import json
import os
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .version import PRODUCT_ID, VERSION


@dataclass
class ReachOpsUpdateInfo:
    available: bool
    current_version: str
    latest_version: str = ""
    reason: str = ""
    manifest: dict[str, Any] | None = None


class ReachOpsUpdateManager:
    """Standalone update helper for ReachOps packaged clients.

    This class intentionally stays self-contained inside the ReachOps client.
    It works with the ReachOps manifest generated by
    tools/write_reachops_update_manifest.py.
    """

    def __init__(self, current_version: str = VERSION, install_dir: str | None = None):
        self.current_version = str(current_version or VERSION).lstrip("v")
        self.install_dir = os.path.abspath(install_dir or os.getcwd())

    def load_manifest(self, source: str | os.PathLike) -> dict[str, Any]:
        source_text = str(source)
        if source_text.startswith(("http://", "https://")):
            with urllib.request.urlopen(source_text, timeout=20) as response:
                payload = response.read().decode("utf-8")
        else:
            payload = Path(source).read_text(encoding="utf-8")
        manifest = json.loads(payload)
        self.validate_manifest(manifest)
        return manifest

    def validate_manifest(self, manifest: dict[str, Any]) -> None:
        if str(manifest.get("product_id") or "") != PRODUCT_ID:
            raise ValueError("manifest product_id mismatch")
        if str(manifest.get("platform") or "") != "windows":
            raise ValueError("manifest platform must be windows")
        version = str(manifest.get("version") or "").strip()
        if not version:
            raise ValueError("manifest version is required")
        installer = manifest.get("installer") or {}
        if not isinstance(installer, dict):
            raise ValueError("manifest installer must be an object")
        if not str(installer.get("sha256") or "").strip():
            raise ValueError("manifest installer.sha256 is required")

    def check_manifest(self, manifest: dict[str, Any]) -> ReachOpsUpdateInfo:
        self.validate_manifest(manifest)
        latest = str(manifest.get("version") or "").lstrip("v")
        comparison = self.compare_versions(self.current_version, latest)
        if comparison < 0:
            return ReachOpsUpdateInfo(True, self.current_version, latest, "new_version_available", manifest)
        if comparison == 0:
            return ReachOpsUpdateInfo(False, self.current_version, latest, "already_latest", manifest)
        return ReachOpsUpdateInfo(False, self.current_version, latest, "current_version_is_newer", manifest)

    def verify_installer(self, installer_path: str | os.PathLike, manifest: dict[str, Any]) -> bool:
        installer = Path(installer_path)
        expected = str(((manifest.get("installer") or {}).get("sha256") or "")).lower().replace("sha256:", "")
        if len(expected) != 64 or any(ch not in "0123456789abcdef" for ch in expected):
            return False
        if not installer.exists() or not installer.is_file():
            return False
        size = int((manifest.get("installer") or {}).get("size_bytes") or 0)
        if size and installer.stat().st_size != size:
            return False
        return self.sha256_file(installer) == expected

    def installer_path_from_manifest(self, manifest: dict[str, Any], base_dir: str | os.PathLike | None = None) -> str:
        installer = manifest.get("installer") or {}
        path = str(installer.get("path") or "").strip()
        if path:
            candidate = Path(path)
            if candidate.is_absolute():
                return str(candidate)
            return str(Path(base_dir or os.getcwd()) / candidate)
        file_name = str(installer.get("file_name") or "").strip()
        if not file_name:
            raise ValueError("manifest installer file_name/path is required")
        return str(Path(base_dir or os.getcwd()) / file_name)

    def silent_install_args(self, installer_path: str | os.PathLike) -> list[str]:
        return [
            str(installer_path),
            "/VERYSILENT",
            "/SUPPRESSMSGBOXES",
            "/FORCECLOSEAPPLICATIONS",
            f'/DIR="{self.install_dir}"',
        ]

    def compare_versions(self, current: str, latest: str) -> int:
        current_parts = self._version_parts(current)
        latest_parts = self._version_parts(latest)
        max_len = max(len(current_parts), len(latest_parts))
        current_parts.extend([0] * (max_len - len(current_parts)))
        latest_parts.extend([0] * (max_len - len(latest_parts)))
        for left, right in zip(current_parts, latest_parts):
            if left < right:
                return -1
            if left > right:
                return 1
        return 0

    def _version_parts(self, value: str) -> list[int]:
        parts = []
        for item in str(value or "0").strip().lstrip("vV").split("."):
            numeric = "".join(ch for ch in item if ch.isdigit())
            parts.append(int(numeric or 0))
        return parts or [0]

    def sha256_file(self, path: str | os.PathLike) -> str:
        digest = hashlib.sha256()
        with Path(path).open("rb") as fh:
            for chunk in iter(lambda: fh.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
