# -*- coding: utf-8 -*-
from __future__ import annotations

import hashlib
import json
import os
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .security_signing import load_key_ring, verify_signed_payload
from .version import BUILD_CHANNEL, PRODUCT_ID, VERSION


@dataclass
class ReachOpsUpdateInfo:
    available: bool
    current_version: str
    latest_version: str = ""
    reason: str = ""
    manifest: dict[str, Any] | None = None


class ReachOpsUpdateManager:
    """Standalone update helper for ReachOps packaged clients.

    This class intentionally stays self-contained inside the ReachOps client.
    It works with the ReachOps manifest generated by
    tools/write_reachops_update_manifest.py.
    """

    def __init__(
        self,
        current_version: str = VERSION,
        install_dir: str | None = None,
        manifest_key_ring: dict[str, str] | None = None,
    ):
        self.current_version = str(current_version or VERSION).lstrip("v")
        self.install_dir = os.path.abspath(install_dir or os.getcwd())
        self.manifest_key_ring = manifest_key_ring

    def load_manifest(self, source: str | os.PathLike) -> dict[str, Any]:
        source_text = str(source)
        require_signature = False
        if source_text.startswith("https://"):
            require_signature = True
            with urllib.request.urlopen(source_text, timeout=20) as response:
                payload = response.read().decode("utf-8")
        elif source_text.startswith("http://"):
            raise ValueError("remote update manifest must use https")
        else:
            payload = Path(source).read_text(encoding="utf-8")
        manifest = json.loads(payload)
        self.validate_manifest(manifest, require_signature=require_signature)
        return manifest

    def validate_manifest(self, manifest: dict[str, Any], require_signature: bool = False) -> None:
        if str(manifest.get("product_id") or "") != PRODUCT_ID:
            raise ValueError("manifest product_id mismatch")
        if str(manifest.get("platform") or "") != "windows":
            raise ValueError("manifest platform must be windows")
        if str(manifest.get("channel") or "") != BUILD_CHANNEL:
            raise ValueError("manifest channel mismatch")
        version = str(manifest.get("version") or "").strip()
        if not version:
            raise ValueError("manifest version is required")
        installer = manifest.get("installer") or {}
        if not isinstance(installer, dict):
            raise ValueError("manifest installer must be an object")
        sha256 = str(installer.get("sha256") or "").lower().replace("sha256:", "")
        if len(sha256) != 64 or any(ch not in "0123456789abcdef" for ch in sha256):
            raise ValueError("manifest installer.sha256 is required")
        try:
            installer_size = int(installer.get("size_bytes") or 0)
        except Exception:
            installer_size = 0
        if installer_size <= 0:
            raise ValueError("manifest installer.size_bytes is required")
        rollback_policy = manifest.get("rollback_policy") if isinstance(manifest.get("rollback_policy"), dict) else {}
        if "allow_downgrade" not in rollback_policy:
            raise ValueError("manifest rollback_policy.allow_downgrade is required")
        minimum_version = str(rollback_policy.get("minimum_version") or "").strip()
        if not minimum_version:
            raise ValueError("manifest rollback_policy.minimum_version is required")
        if self.compare_versions(self.current_version, minimum_version) < 0:
            raise ValueError("manifest rollback policy blocks this client version")
        if require_signature:
            signature_ok, signature_reason = verify_signed_payload(
                manifest,
                key_ring=self.manifest_key_ring if self.manifest_key_ring is not None else load_key_ring(),
                signature_field="manifest_signature",
            )
            if not signature_ok:
                raise ValueError(f"manifest signature invalid: {signature_reason}")

    def check_manifest(self, manifest: dict[str, Any]) -> ReachOpsUpdateInfo:
        self.validate_manifest(manifest)
        latest = str(manifest.get("version") or "").lstrip("v")
        comparison = self.compare_versions(self.current_version, latest)
        rollback_policy = manifest.get("rollback_policy") if isinstance(manifest.get("rollback_policy"), dict) else {}
        allow_downgrade = bool(rollback_policy.get("allow_downgrade"))
        if comparison < 0:
            return ReachOpsUpdateInfo(True, self.current_version, latest, "new_version_available", manifest)
        if comparison == 0:
            return ReachOpsUpdateInfo(False, self.current_version, latest, "already_latest", manifest)
        if allow_downgrade:
            return ReachOpsUpdateInfo(True, self.current_version, latest, "rollback_available", manifest)
        return ReachOpsUpdateInfo(False, self.current_version, latest, "current_version_is_newer", manifest)

    def verify_installer(self, installer_path: str | os.PathLike, manifest: dict[str, Any]) -> bool:
        installer = Path(installer_path)
        expected = str(((manifest.get("installer") or {}).get("sha256") or "")).lower().replace("sha256:", "")
        if len(expected) != 64 or any(ch not in "0123456789abcdef" for ch in expected):
            return False
        if not installer.exists() or not installer.is_file():
            return False
        size = int((manifest.get("installer") or {}).get("size_bytes") or 0)
        if size and installer.stat().st_size != size:
            return False
        return self.sha256_file(installer) == expected

    def installer_path_from_manifest(self, manifest: dict[str, Any], base_dir: str | os.PathLike | None = None) -> str:
        installer = manifest.get("installer") or {}
        path = str(installer.get("path") or "").strip()
        if path:
            return path
        file_name = str(installer.get("file_name") or "").strip()
        if not file_name:
            raise ValueError("manifest installer file_name/path is required")
        return str(Path(base_dir or os.getcwd()) / file_name)

    def silent_install_args(self, installer_path: str | os.PathLike) -> list[str]:
        return [
            str(installer_path),
            "/VERYSILENT",
            "/SUPPRESSMSGBOXES",
            "/FORCECLOSEAPPLICATIONS",
            f'/DIR="{self.install_dir}"',
        ]

    def compare_versions(self, current: str, latest: str) -> int:
        current_parts = self._version_parts(current)
        latest_parts = self._version_parts(latest)
        max_len = max(len(current_parts), len(latest_parts))
        current_parts.extend([0] * (max_len - len(current_parts)))
        latest_parts.extend([0] * (max_len - len(latest_parts)))
        for left, right in zip(current_parts, latest_parts):
            if left < right:
                return -1
            if left > right:
                return 1
        return 0

    def _version_parts(self, value: str) -> list[int]:
        parts = []
        for item in str(value or "0").strip().lstrip("vV").split("."):
            numeric = "".join(ch for ch in item if ch.isdigit())
            parts.append(int(numeric or 0))
        return parts or [0]

    def sha256_file(self, path: str | os.PathLike) -> str:
        digest = hashlib.sha256()
        with Path(path).open("rb") as fh:
            for chunk in iter(lambda: fh.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
